### ISSUE TITLE
Palm rejection issues on Ipad

### ISSUE THREAD

**Issue by gastronomical** [thenickdude/chickenpaint#36]
Hello, thanks for creating this wonderful port of a beloved drawing applet!

I've noticed on Ipad + Apple Pencil, there's occasional palm rejection issues if your palm makes contact anywhere on the screen before the pen does. This can be observed as straight lines joining from where your palm makes contact to the initial mark of your pen.
![1627964236945](https://user-images.githubusercontent.com/73634094/127963647-b5a698ea-4a96-47b5-8c71-7820a18c19df.jpg)

Ipad adoption is increasing among artists so I think it'd be a worthwhile endeavor to improve palm rejection.

**Comment by thenickdude** [comment]
I think the best I can do there is hope that iOS Safari labels the pointer events with either pen or finger tags. I'll find a test you can use to identify if that is available.

**Comment by gastronomical** [comment]
Sounds good, I'll be happy to help.

**Comment by thenickdude** [comment]
Please try dragging your pointer around this page and see if the labelling distinguishes between your pen and finger touch, and if so let me know how it differs, or if possible take a screenshot:

https://patrickhlauke.github.io/touch/tracker/multi-touch-tracker-pointer-hud.html

**Comment by gastronomical** [comment]
Labelling indeed tells them apart. For curiosity, i found it supports multiple touches as well.
![E928302A-8141-4C42-B824-7AC866032822](https://user-images.githubusercontent.com/73634094/128273539-de32c798-7904-44c9-832c-827bc9a52ede.jpeg)
![8E8321A3-35FA-4F9E-B9F3-7BA56F18D641](https://user-images.githubusercontent.com/73634094/128273543-b04e7329-c6b4-42a4-8e75-c0b8411939e9.jpeg)
![8342AFCE-5AAF-4945-9D14-457A03364BDB](https://user-images.githubusercontent.com/73634094/128273549-6c4e34ea-4315-4d5e-8a88-bb0915f4afc2.jpeg)
![54103732-5CCD-4381-AD10-6E3EE9035983](https://user-images.githubusercontent.com/73634094/128273551-43a533a1-f236-4edf-80f3-00e5c3181938.jpeg)

**Comment by thenickdude** [comment]
Okay, I should be able to automatically disable touch if a pen is detected then, thanks!

It's interesting that the touch pressure events don't include any pressure information... I assume that attempting to draw with them creates an extremely thin line unless the "enable pressure" tickbox next to "brush size" is deselected? On my Android I get pressure information corresponding to how large the contact area is between my finger and the device.

**Comment by gastronomical** [comment]
> I assume that attempting to draw with them creates an extremely thin line unless the "enable pressure" tickbox next to "brush size" is deselected? 

That’s correct. As its selected it behaves as the brush is 1px, regardless of brush size.
also if opacity is set, lines become invisible with touch.
![C6D5984C-D319-4B01-A477-3F4F0798A228](https://user-images.githubusercontent.com/73634094/128284511-ef46703c-678d-4ba8-baae-2f309cad67a0.jpeg)

When opacity is disabled, a weird (but cool) back and forth line pattern occurs when drawing with two fingers seen above.

**Comment by satopian** [comment]
The images have already been submitted, but I will also submit a video for the test taken by my acquaintance.
[For Chickenpaint Official. Palm test movie01.  / Twitter](https://twitter.com/ankokunoteatime/status/1423033591898935300)

**Comment by thenickdude** [comment]
Please try the latest version here (you'll need to refresh the page to get the new code):

https://thenickdude.github.io/chickenpaint-example/

When it sees a pen present it should now disable touch-drawing for the rest of the session. I've also fixed the pressure readings when drawing using fingers so the lines should no longer be invisible or tiny when not using a pen.

**Comment by gastronomical** [comment]
Palm rejection issue still exists. I’m not sure if it has to do with their pencil technology (AES is not detected until it touches the display). Opacity causing invisible lines seems to be fixed except for pencil and watercolour brush. However turning on pressure still results in 1px lines.

**Comment by thenickdude** [comment]
This really sounds like the previous unfixed version of the code is being run, maybe try using Incognito mode.

**Comment by satopian** [comment]
I asked a Japanese drawing board user who uses an iPad to try it.
It seems that the problem of palm rejection, the problem of double tap zoom, and the problem of screen selection have all been solved.

**Comment by gastronomical** [comment]
Im still getting the same behaviour after turning off and turning on the device. I did incognito mode and shift refresh with no luck. Maybe I simply can’t get the cache to refresh if another user is reporting it fixed.

**Comment by thenickdude** [comment]
Which iOS version?

I've pushed a new version of the chickenpaint example now which bumps the resource URLs. This should force them to be loaded fresh instead of re-used from cache, you could give it another go:

https://thenickdude.github.io/chickenpaint-example/?1

You can tell you're running the new version if the heading at the top of the page reads "ChickenPaint integration example (bumped)"

**Comment by gastronomical** [comment]
I’m on iOS 14.6. Yeah, still getting the same behaviour even with the bumped version. I have no idea why I can’t see any of the changes…tried on both safari and chromium.  Really weird.

**Comment by thenickdude** [comment]
I found an additional problem with Safari where if it detects the pointer as a "mouse" it doesn't report pressure values either, leading to the invisible ink problem. I swear this was working yesterday, so this might be new in 14.6 / Safari Technology Preview 129.

Please try it again, the header should say "bumped 4" this time.

After using the pen once it should reject palm touches after that, but not before (since ChickenPaint can't tell a pen is being used until it sees it)

**Comment by gastronomical** [comment]
Everything is working now, thank you! For both chromium and safari.
Cheers nick.

**Comment by thenickdude** [comment]
This should be fixed in the new NPM 0.3.1 release now
